# Generated by Django 5.0.6 on 2026-07-11 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='区县名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='区县代码')),
                ('status', models.CharField(default='active', max_length=10, verbose_name='状态')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '区县',
                'verbose_name_plural': '区县',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='机构名称')),
                ('type', models.CharField(choices=[('shelter', '捕捉点'), ('hospital', '医院'), ('community', '小区')], max_length=20, verbose_name='机构类型')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='地址')),
                ('contact', models.CharField(blank=True, default='', max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('status', models.CharField(default='active', max_length=10, verbose_name='状态')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='core.district', verbose_name='所属区县')),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
                'ordering': ['id'],
            },
        ),
    ]
