# Generated by Django 5.0.6 on 2026-07-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='is_city',
            field=models.BooleanField(default=False, help_text='市级区域用于市管理员/捕捉点操作员归属', verbose_name='是否市级'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('shelter', '捕捉点'), ('hospital', '医院'), ('community', '小区')], max_length=20, verbose_name='机构类型'),
        ),
    ]
