# Generated by Django 5.0.6 on 2026-07-12 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('core', '0002_district_is_city_alter_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captures', to='core.institution', verbose_name='捕捉点'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='shelter_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='捕捉点名称'),
        ),
        migrations.AlterField(
            model_name='material',
            name='shelter_stock',
            field=models.IntegerField(default=0, verbose_name='捕捉点库存'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='core.institution', verbose_name='捕捉点'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transfers', to='core.institution', verbose_name='发出捕捉点'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_shelter_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='发出捕捉点名称'),
        ),
    ]
