# Generated by Django 5.0.6 on 2026-07-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_capture_shelter_alter_capture_shelter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='ledger_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='台账编号'),
        ),
    ]
