# Generated by Django 5.0.6 on 2026-07-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_add_treatment_ledger_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='status',
            field=models.CharField(choices=[('pending_claim', '待领出'), ('completed', '已完成'), ('cancelled', '已取消')], default='completed', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='type',
            field=models.CharField(choices=[('purchase', '采购入库'), ('dispatch', '下发'), ('receive', '医院签收'), ('consume', '消耗'), ('adjustment', '异动')], max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('in_transit', '在途'), ('in_treatment', '待诊疗'), ('pending_adopt', '待领养'), ('pending_claim', '待领出'), ('adopted', '已领养'), ('released', '已放养'), ('euthanized', '已安乐死'), ('owner_returned', '主人领回')], default='in_transit', max_length=20, verbose_name='状态'),
        ),
    ]
