# Generated by Django 5.0.6 on 2026-08-06 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "business",
            "0004_alter_adoption_status_alter_materialtransaction_type_and_more",
        ),
        ("core", "0002_district_is_city_alter_institution_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdoptionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pet_code",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="宠物编号"
                    ),
                ),
                (
                    "applicant_name",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="申请人姓名"
                    ),
                ),
                (
                    "applicant_phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "applicant_id_card",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="身份证号"
                    ),
                ),
                (
                    "applicant_address",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="居住地址"
                    ),
                ),
                (
                    "qualification",
                    models.TextField(
                        blank=True, default="", verbose_name="领养资质说明"
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="领养理由"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "hospital_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="受理机构名称",
                    ),
                ),
                (
                    "review_note",
                    models.TextField(blank=True, default="", verbose_name="审核意见"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adoption_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adoption_applications",
                        to="core.institution",
                        verbose_name="受理机构",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoption_applications",
                        to="business.pet",
                        verbose_name="宠物",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adoption_applications_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "领养申请单",
                "verbose_name_plural": "领养申请单",
                "ordering": ["-id"],
            },
        ),
    ]
